# Generated by Django 4.2.1 on 2023-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="tag",
            field=models.ManyToManyField(blank=True, to="album.tag"),
        ),
    ]
